### ISSUE TITLE
Add lol-chaining

### ISSUE THREAD

**Issue by autophagy** [autophagy/forebodere#1]
Due to popular demand, the bot should react when sequential "lol"s are written into a channel within a given time frame. When a user says "lol", it should start a 10 second timeout. Each subsequent lol refreshes this timeout. After the timeout expires, the following message is posted into the channel depnding on how many "lol"s were posted in sequence:

- 3: multilol
- 4: ultralol
- 5: M-M-M-MONSTERLOL

Known Issues:

- ~~Triggers if sentences start with "lol", not just discreet instances~~
- ~~Takes no account of the people saying it~~
- ~~Only reacts on "lol", should react on several words~~
- Not customizable

**Comment by RedStarParcels** [comment]
Please add filtering that lols can only be issued via multiple discreet usernames to remove stolen valour and self-activation of the lol chain.

**Comment by autophagy** [comment]
CLOSED: WONTFIX, NOT BUG BUT FEATURE, PEBCAK
